
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 23;
  public static final int SEMICOLON = 26;
  public static final int ELSE = 5;
  public static final int CROTOFUNC = 10;
  public static final int RBRACE = 31;
  public static final int RPAREN = 29;
  public static final int OR = 24;
  public static final int EQUAL = 17;
  public static final int WHILE = 6;
  public static final int DIVISION = 16;
  public static final int CONSTANT = 9;
  public static final int NOT = 25;
  public static final int IDENTIFIER = 34;
  public static final int RETURN = 8;
  public static final int GREATER_EQUAL = 21;
  public static final int DIFFERENT = 18;
  public static final int GREATER = 19;
  public static final int IF = 4;
  public static final int LBRACE = 30;
  public static final int LPAREN = 28;
  public static final int BOOLEAN = 2;
  public static final int COMMA = 27;
  public static final int LOWER = 20;
  public static final int EOF = 0;
  public static final int SUBTRACTION = 14;
  public static final int MULTIPLICATION = 15;
  public static final int MAIN = 11;
  public static final int BREAK = 7;
  public static final int INTEGER_VALUE = 32;
  public static final int error = 1;
  public static final int ASSIGNMENT = 12;
  public static final int INTEGER = 3;
  public static final int BOOLEAN_VALUE = 33;
  public static final int ADDITION = 13;
  public static final int LOWER_EQUAL = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INTEGER",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "RETURN",
  "CONSTANT",
  "CROTOFUNC",
  "MAIN",
  "ASSIGNMENT",
  "ADDITION",
  "SUBTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "EQUAL",
  "DIFFERENT",
  "GREATER",
  "LOWER",
  "GREATER_EQUAL",
  "LOWER_EQUAL",
  "AND",
  "OR",
  "NOT",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "INTEGER_VALUE",
  "BOOLEAN_VALUE",
  "IDENTIFIER"
  };
}

